In [1]:
import numpy as np

In this script, we would like to build a simple, generalized neural network with n features (each input data has n values) and m outputs with only one hidden layer with k neurons.

In [2]:
dataset = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0]])
output = np.array([[0, 0, 1], [1, 0, 0], [1, 1, 0], [0, 1, 1], [0, 0, 1]])
print("The data set is: \n", dataset, "\n")
print("The output is: \n", output)

The data set is: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]] 

The output is: 
 [[0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]]


In [6]:
#Augment the input matrix to implement also the bias parameter on the input layer
b1 = np.ones([dataset.shape[0], 1])
dataset1 = np.hstack((dataset, b1))

#number of neurons in the first hidden layer
nn1 = 5

#number of neurons in the second hidden layer
nn2 = 4

#initialize the first weight matrix:
W_1 = np.random.random([dataset1.shape[1], nn1])

#intialize the second weight matrix, consider also the bias parameter:
W_2 = np.random.random([nn1 + 1, nn2])

#intialize the third weight matrix, consider also the bias parameter:
W_3 = np.random.random([nn2 + 1, output.shape[1]])

#activation function:
def sig(x):
    return 1 / (1 + np.exp(-x))

#derivative of sigmoid:
def dsig(x):
    return x * (1 - x)

In [7]:
#learning rate
lr =  0.9

In [8]:
i = 0
err = 100
while i<100000:
    if err < 1e-2:
        break
        
    i += 1
    
    #update the predicted values:
    z1 = sig(np.dot(dataset1, W_1))
    
    #augment z1 to include the bias parameter in the first hidden layer
    b2 = np.ones([z1.shape[0], 1])
    z1 = np.hstack((z1, b2))
    
    z2 = sig(np.dot(z1, W_2))
    
    #augment z2 to include the bias parameter in the second hidden layer
    b3 = np.ones([z2.shape[0], 1])
    z2 = np.hstack((z2, b3))
    
    pred_out = sig(np.dot(z2, W_3))
    
    #compute:
    err = 0.5 * np.linalg.norm(output - pred_out, 2)
    
    #back propagation using gradient descent method:
    dW_3 = np.dot(z2.T, -(output - pred_out) * dsig(pred_out))
    
    #truncate the bias for the back propagation of the first layer
    z1t = z1[:,:-1]
    z2t = z2[:,:-1]
    W_3t = W_3[:-1,:]
    W_2t = W_2[:-1,:]
    
    dW_2 = np.zeros_like(W_2)
    for j in range(dW_2.shape[0]):
        for k in range(dW_2.shape[1]):
            dW_2[j, k] = np.dot(W_3t[k,:], np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(z2t)[:,k] * z1[:,j]))
            
    dW_1 = np.dot(dataset1.T, dsig(z1t) * np.dot(np.dot(-(output - pred_out) * dsig(pred_out), W_3t.T) * dsig(z2t), W_2t.T))
    
    #update the weight matrix
    W_1 -= lr * dW_1
    W_2 -= lr * dW_2
    W_3 -= lr * dW_3
    

print("Finish with",i, "iteration(s) with error", err,".")
print("\nThe weight matrix from the input to the hidden layer: \n", W_1)
print("\nThe weight matrix from the hidden to the output layer: \n", W_2)
print("\nThe final predicted output: \n", pred_out)

Finish with 21299 iteration(s) with error 0.009999745487924865 .

The weight matrix from the input to the hidden layer: 
 [[-0.26072374  3.09883436  4.93450776  3.78179036  4.92393358]
 [ 0.42663782  3.45541237  1.70832811  1.55882795  2.6315403 ]
 [ 1.56184207  0.8466925  -0.92719815 -0.41484851 -1.16132079]
 [ 1.39102347 -2.56942594 -3.24873103 -2.6563054  -4.17801192]]

The weight matrix from the hidden to the output layer: 
 [[-1.72842278 -3.05342594 -0.99596635  1.64354495]
 [-0.61251666  0.7784991   5.51907412  1.22986404]
 [ 4.6214834   4.21962452  3.15077529  1.42246321]
 [ 2.28648278  2.20657697  4.10243655  1.72624193]
 [ 4.47388422  5.90168358  4.4497314   1.28251628]
 [-2.00980203 -5.77343175 -4.2597204   2.35028627]]

The final predicted output: 
 [[5.56544825e-04 7.10902078e-03 9.99551657e-01]
 [9.99994484e-01 1.01318088e-02 5.94351403e-06]
 [9.91847678e-01 9.88712936e-01 8.22793258e-03]
 [9.26163637e-03 9.92677634e-01 9.90639672e-01]
 [6.37588908e-04 6.62587155e-03 9.994