In [2]:
import numpy as np

In this script, we would like to build a simple, generalized neural network with n features (each input data has n values) and m outputs with only one hidden layer with k neurons.

In [3]:
dataset = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0]])
output = np.array([[0, 0, 1], [1, 0, 0], [1, 1, 0], [0, 1, 1], [0, 0, 1]])
print("The data set is: \n", dataset, "\n")
print("The output is: \n", output)

The data set is: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]] 

The output is: 
 [[0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]]


In [9]:
#Augment the input matrix to implement also the bias parameter on the input layer
b1 = np.ones([dataset.shape[0], 1])
dataset1 = np.hstack((dataset, b1))

#number of neurons in the first hidden layer
nn1 = 3

#number of neurons in the second hidden layer
nn2 = 4

#initialize the first weight matrix:
W_1 = np.random.random([dataset1.shape[1], nn1])

#intialize the second weight matrix, consider also the bias parameter:
W_2 = np.random.random([nn1 + 1, nn2])

#intialize the third weight matrix, consider also the bias parameter:
W_3 = np.random.random([nn2 + 1, output.shape[1]])

#activation function:
def sig(x):
    return 1 / (1 + np.exp(-x))

#derivative of sigmoid:
def dsig(x):
    return x * (1 - x)

In [41]:
#learning rate
lr =  0.9

In [5]:
i = 0
err = 100
while i<100000:
    if err < 1e-2:
        break
        
    i += 1
    
    #update the predicted values:
    z1 = sig(np.dot(dataset1, W_1))
    
    #augment z1 to include the bias parameter in the first hidden layer
    b2 = np.ones([z1.shape[0], 1])
    z1 = np.hstack((z1, b2))
    
    z2 = sig(np.dot(z1, W_2))
    
    #augment z2 to include the bias parameter in the second hidden layer
    b3 = np.ones([z2.shape[0], 1])
    z2 = np.hstack((z2, b3))
    
    pred_out = sig(np.dot(z2, W_3))
    
    #compute:
    err = 0.5 * np.linalg.norm(output - pred_out, 2)
    
    #back propagation using gradient descent method:
    dW_3 = np.dot(z2.T, -(output - pred_out) * dsig(pred_out))
    
    dW_2 = np.zeros_like(W_2)
    for j in range(dW_2.shape[0]):
        for k in range(dW_2.shape[1]):
            dW_2[j, k] = np.dot(W_3[k,:], np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(z2)[:,k] * z1[:,j]))
            
    dW_1 = np.zeros_like(W_1)
    for p in range(dW_3.shape[0]):
        for q in range(dW_2.shape[1]):
            dW_3[p,q] = np.dor()
    
    #update the weight matrix
    W_1 -= lr * dW_1
    W_2 -= lr * dW_2
    W_3 -= lr * dW_3
    

print("Finish with",i, "iteration(s) with error", err,".")
print("\nThe weight matrix from the input to the hidden layer: \n", W_1)
print("\nThe weight matrix from the hidden to the output layer: \n", W_2)
print("\nThe final predicted output: \n", pred_out)

ValueError: operands could not be broadcast together with shapes (5,3) (5,4) 

In [18]:
dW_2 = np.zeros_like(W_2)

In [21]:
for j in range(dW_2.shape[0]):
    for k in range(dW_2.shape[1]):
        dW_2[j, k] = np.dot(W_3[k,:], np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(z2)[:,k] * z1[:,j]))

In [22]:
dW_2

array([[0.04312137, 0.0148387 , 0.03289264, 0.03396959],
       [0.04186562, 0.01442684, 0.03066177, 0.03282835],
       [0.04652657, 0.0160162 , 0.03401329, 0.03644184],
       [0.06038092, 0.02059964, 0.04147286, 0.04683053]])