In [50]:
import numpy as np

In this script, we would like to build a simple, generalized neural network with n features (each input data has n values) and m outputs with only one hidden layer with k neurons.

In [51]:
dataset = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0]])
output = np.array([[0, 0, 1], [1, 0, 0], [1, 1, 0], [0, 1, 1], [0, 0, 1]])
print("The data set is: \n", dataset, "\n")
print("The output is: \n", output)

The data set is: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]] 

The output is: 
 [[0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]]


In [52]:
#Augment the input matrix to implement also the bias parameter on the input layer
#b1 = np.ones([dataset.shape[0], 1])
#dataset1 = np.hstack((dataset, b1))

#number of neurons in the first hidden layer
nn1 = 6

#number of neurons in the second hidden layer
nn2 = 7

#initialize the first weight matrix:
W_1 = np.random.random([dataset.shape[1], nn1])

#intialize the second weight matrix, consider also the bias parameter:
W_2 = np.random.random([nn1, nn2])

#intialize the third weight matrix, consider also the bias parameter:
W_3 = np.random.random([nn2, output.shape[1]])

#activation function:
def sig(x):
    return 1 / (1 + np.exp(-x))

#derivative of sigmoid:
def dsig(x):
    return x * (1 - x)

In [53]:
#learning rate
lr =  0.9

In [97]:
i = 0
err = 100
while i<100000:
    if err < 1e-2:
        break
        
    i += 1
    
    #update the predicted values:
    z1 = sig(np.dot(dataset, W_1))
    
    #augment z1 to include the bias parameter in the first hidden layer
    #b2 = np.ones([z1.shape[0], 1])
    #z1 = np.hstack((z1, b2))
    
    z2 = sig(np.dot(z1, W_2))
    
    #augment z2 to include the bias parameter in the second hidden layer
    #b3 = np.ones([z2.shape[0], 1])
    #z2 = np.hstack((z2, b3))
    
    pred_out = sig(np.dot(z2, W_3))
    
    #compute:
    err = 0.5 * np.linalg.norm(output - pred_out, 2)
    
    #back propagation using gradient descent method:
    dW_3 = np.dot(z2.T, -(output - pred_out) * dsig(pred_out))
    
    dW_2 = np.zeros_like(W_2)
    for j in range(dW_2.shape[0]):
        for k in range(dW_2.shape[1]):
            dW_2[j, k] = np.dot(W_3[k,:], np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(z2)[:,k] * z1[:,j]))
            
    dW_1 = np.dot(dataset.T, dsig(z1) * np.dot(np.dot(-(output - pred_out) * dsig(pred_out), W_3.T) * dsig(z2), W_2.T))
    
    #update the weight matrix
    W_1 -= lr * dW_1
    W_2 -= lr * dW_2
    W_3 -= lr * dW_3
    

print("Finish with",i, "iteration(s) with error", err,".")
print("\nThe weight matrix from the input to the hidden layer: \n", W_1)
print("\nThe weight matrix from the hidden to the output layer: \n", W_2)
print("\nThe final predicted output: \n", pred_out)

Finish with 12355 iteration(s) with error 0.00999953618603657 .

The weight matrix from the input to the hidden layer: 
 [[ 2.33123612  3.67168716 -1.32746912 -5.3491659   1.98379641  4.28145767]
 [ 1.70327783  2.95022597  0.65853877 -2.85393201  3.74041642  1.29855204]
 [ 1.74106384 -0.31152799 -0.66422908  2.44650737 -3.96369545 -3.43557513]]

The weight matrix from the hidden to the output layer: 
 [[ 1.79872578  2.3014878  -2.63245317  0.96144335  0.83857981  0.11701823
  -0.82139644]
 [ 1.17898524  4.18004357 -2.43102516  1.41455173  1.69715039  0.05280351
  -0.08106335]
 [ 1.52289851 -1.24914025 -0.0929863   0.83972971 -1.34200796  1.58858661
  -1.5734045 ]
 [ 1.41951298 -6.9866366  -5.85225147  1.9407404  -6.61741458  1.93690174
  -6.35768555]
 [ 1.61360816  0.06691401  5.12994819  1.43605276 -1.36112693  1.10861093
   1.39719728]
 [ 1.69367558 -0.7865541   3.8124351   1.34490929  1.55034129 -0.49912995
   3.56280352]]

The final predicted output: 
 [[2.59691629e-04 9.93528246e-