In [1]:
import numpy as np

In this script, we would like to build a simple, generalized neural network with n features (each input data has n values) and m outputs with only one hidden layer with k neurons.

In [2]:
dataset = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0]])
output = np.array([[0, 0, 1], [1, 0, 0], [1, 1, 0], [0, 1, 1], [0, 0, 1]])
print("The data set is: \n", dataset, "\n")
print("The output is: \n", output)

The data set is: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]] 

The output is: 
 [[0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]]


In [3]:
#Augment the input matrix to implement also the bias parameter on the input layer
b1 = np.ones([dataset.shape[0], 1])
dataset1 = np.hstack((dataset, b1))

#number of neurons
nn = 20

#initialize the first weight matrix:
W_1 = np.random.random([dataset1.shape[1], nn])

#intialize the second weight matrix, consider also the bias parameter:
W_2 = np.random.random([nn + 1, output.shape[1]])

#activation function:
def sig(x):
    return 1 / (1 + np.exp(-x))

#derivative of sigmoid:
def dsig(x):
    return x * (1 - x)

In [4]:
#learning rate
lr =  0.9

In [5]:
i = 0
err = 100
while i<100000:
    if err < 1e-2:
        break
        
    i += 1
    
    #update the predicted values:
    z = sig(np.dot(dataset1, W_1))
    
    #augment z to include the bias parameter in the hidden layer
    b2 = np.ones([z.shape[0], 1])
    z = np.hstack((z, b2))
    pred_out = sig(np.dot(z, W_2))
    
    #compute:
    err = 0.5 * np.linalg.norm(output - pred_out, 2)
    
    #back propagation using gradient descent method:
    dW_2 = np.dot(z.T, -(output - pred_out) * dsig(pred_out))
    dW_1 = np.zeros_like(W_1)
    for j in range(dW_1.shape[0]):
        for k in range(dW_1.shape[1]):
            dW_1[j, k] = np.dot(W_2[k,:], np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(z)[:,k] * dataset1[:,j]))
    
    #update the weight matrix
    W_1 -= lr * dW_1
    W_2 -= lr * dW_2
    

print("Finish with",i, "iteration(s) with error", err,".")
print("\nThe weight matrix from the input to the hidden layer: \n", W_1)
print("\nThe weight matrix from the hidden to the output layer: \n", W_2)
print("\nThe final predicted output: \n", pred_out)

Finish with 6367 iteration(s) with error 0.00999924100821376 .

The weight matrix from the input to the hidden layer: 
 [[-3.73757143e+00 -8.41620693e-01  3.58971720e+00  2.64321966e+00
  -7.98867162e-01 -1.46007131e+00  2.42456843e+00 -2.20269385e+00
   4.57887896e+00  1.91588702e-01  3.66608609e+00  1.32421373e+00
  -1.18923286e+00  3.69821163e+00  1.26876257e+00  1.85356265e+00
   2.30511335e+00 -3.44032277e+00 -2.77513151e+00 -4.17679646e+00]
 [ 2.03696693e+00  1.40769714e+00  2.80389143e+00  2.05595050e+00
   1.82409492e+00  2.37464659e+00  8.88539173e-01  2.87150294e+00
   4.03415485e+00  7.08632654e-01  3.55389206e+00  4.94066900e-01
  -1.03118848e-01  2.20660205e+00  1.21693672e+00  1.83115242e+00
   1.95656675e+00  8.90635708e-01  3.44036586e+00  3.01412488e+00]
 [-6.75051372e-02 -4.94052544e-01  4.21093329e-01 -1.52137933e+00
  -8.80188950e-04 -3.29764003e-01 -7.14598167e-01  1.74005043e-01
   4.10796543e-01  1.45071169e-02  2.47858727e-01 -3.49746703e-02
  -4.64962029e-01 -1