In [1]:
import numpy as np

In this script, we would like to build a simple neural network with 3 features (each input data has 3 values) and 1 output with only one hidden layer with 5 neurons.

In [2]:
dataset = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0]])
output = np.array([[0], [1], [1], [0], [0]])
print("The data set is: \n", dataset, "\n")
print("The output is: \n", output)

The data set is: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]] 

The output is: 
 [[0]
 [1]
 [1]
 [0]
 [0]]


In [3]:
#Augment the input matrix to implement also the bias parameter on the input layer
b1 = np.ones([dataset.shape[0], 1])
dataset1 = np.hstack((dataset, b1))

#number of neurons
nn = 8

#initialize the first weight matrix:
W_1 = np.random.random([dataset1.shape[1], nn])

#intialize the second weight matrix, consider also the bias parameter:
W_2 = np.random.random([nn + 1, 1])

#activation function:
def sig(x):
    return 1 / (1 + np.exp(-x))

#derivative of sigmoid:
def dsig(x):
    return x * (1 - x)

In [4]:
#learning rate
lr =  0.9

In [5]:
i = 0
err = 100
while i<5000:
    if err < 1e-2:
        break
        
    i += 1
    
    #update the predicted values:
    z = sig(np.dot(dataset1, W_1))
    
    #augment z to include the bias parameter in the hidden layer
    b2 = np.ones([z.shape[0], 1])
    z = np.hstack((z, b2))
    pred_out = sig(np.dot(z, W_2))
    
    #compute:
    err = 0.5 * np.linalg.norm(output - pred_out, 2)
    
    #back propagation using gradient descent method:
    dW_2 = np.dot(z.T, -(output - pred_out) * dsig(pred_out))
    dW_1 = np.zeros_like(W_1)
    for j in range(dW_1.shape[0]):
        for k in range(dW_1.shape[1]):
            dW_1[j, k] = W_2[k] * np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(z)[:,k] * dataset1[:,j] )
    
    #update the weight matrix
    W_1 -= lr * dW_1
    W_2 -= lr * dW_2
    

print("Finish with",i, "iteration(s) with error", err,".")
print("\nThe weight matrix from the input to the hidden layer: \n", W_1)
print("\nThe weight matrix from the hidden to the output layer: \n", W_2)
print("\nThe final predicted output: \n", pred_out)

Finish with 2879 iteration(s) with error 0.009998058694739083 .

The weight matrix from the input to the hidden layer: 
 [[ 1.07055900e+00 -2.73748244e+00  9.90252917e-01  4.41173573e+00
   9.60353330e-01  1.75184234e+00  2.87627849e+00 -3.39476444e-01]
 [ 4.55060373e-01  1.60717015e-01  5.69479455e-02 -1.18508142e-03
   1.70987097e-01  2.60175540e-01  1.58062166e-02  4.39557729e-01]
 [-1.56411545e-02  1.06691735e-01  5.33856979e-01 -4.67285676e-02
   4.81405925e-01  1.46933372e-01  2.72177775e-01  3.70232962e-01]
 [-9.08565192e-02  1.13149608e+00  7.14288218e-02 -2.09546081e+00
  -9.50846237e-02 -8.66722938e-01 -1.59869906e+00  9.52690969e-01]]

The weight matrix from the hidden to the output layer: 
 [[ 0.60189708]
 [-3.6798676 ]
 [ 0.41424762]
 [ 5.33341587]
 [ 0.41999303]
 [ 1.57507001]
 [ 3.1095633 ]
 [-1.30744619]
 [-3.35470865]]

The final predicted output: 
 [[0.0089374 ]
 [0.99048061]
 [0.99094574]
 [0.0090248 ]
 [0.00811924]]
