In [25]:
import numpy as np

In this script, we would like to build a simple, generalized neural network with n features (each input data has n values) and m outputs with only one hidden layer with k neurons.

In [30]:
dataset = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0]])
output = np.array([[0, 0, 1], [1, 0, 0], [1, 1, 0], [0, 1, 1], [0, 0, 1]])
print("The data set is: \n", dataset, "\n")
print("The output is: \n", output)

The data set is: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]] 

The output is: 
 [[0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]]


In [40]:
#Augment the input matrix to implement also the bias parameter on the input layer
b1 = np.ones([dataset.shape[0], 1])
dataset1 = np.hstack((dataset, b1))

#number of neurons
nn = 20

#initialize the first weight matrix:
W_1 = np.random.random([dataset1.shape[1], nn])

#intialize the second weight matrix, consider also the bias parameter:
W_2 = np.random.random([nn + 1, output.shape[1]])

#activation function:
def sig(x):
    return 1 / (1 + np.exp(-x))

#derivative of sigmoid:
def dsig(x):
    return x * (1 - x)

In [41]:
#learning rate
lr =  0.9

In [42]:
i = 0
err = 100
while i<100000:
    if err < 1e-2:
        break
        
    i += 1
    
    #update the predicted values:
    z = sig(np.dot(dataset1, W_1))
    
    #augment z to include the bias parameter in the hidden layer
    b2 = np.ones([z.shape[0], 1])
    z = np.hstack((z, b2))
    pred_out = sig(np.dot(z, W_2))
    
    #compute:
    err = 0.5 * np.linalg.norm(output - pred_out, 2)
    
    #back propagation using gradient descent method:
    dW_2 = np.dot(z.T, -(output - pred_out) * dsig(pred_out))
    dW_1 = np.zeros_like(W_1)
    for j in range(dW_1.shape[0]):
        for k in range(dW_1.shape[1]):
            dW_1[j, k] = np.dot(W_2[k,:], np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(z)[:,k] * dataset1[:,j]))
    
    #update the weight matrix
    W_1 -= lr * dW_1
    W_2 -= lr * dW_2
    

print("Finish with",i, "iteration(s) with error", err,".")
print("\nThe weight matrix from the input to the hidden layer: \n", W_1)
print("\nThe weight matrix from the hidden to the output layer: \n", W_2)
print("\nThe final predicted output: \n", pred_out)

Finish with 8020 iteration(s) with error 0.009999889543683154 .

The weight matrix from the input to the hidden layer: 
 [[ 5.21355026e+00 -1.79035749e+00  1.38728654e+00 -9.93489007e-01
  -4.77602437e-01  7.30297976e-01 -6.86853711e-01  3.96058359e+00
   3.28974682e+00  1.11240501e+00  1.46095030e+00 -2.76527970e+00
  -2.53484403e+00  2.26706921e-01 -3.91178721e+00  2.63835610e+00
   2.43251381e+00  4.60445869e+00  3.20155361e+00  1.88556817e+00]
 [ 4.82350612e+00  1.97972131e-01  3.68655752e-01  2.90886186e-01
   1.35471660e+00  2.14356036e-01 -1.11302545e+00  3.52720056e+00
  -1.86162091e-01  6.79334935e-01 -4.83551197e-02  7.91421937e-01
   3.29499691e+00  3.62829599e-01  3.28193143e-01 -1.70288073e+00
   4.82066391e-02  4.75571187e+00 -2.13417037e+00  1.72413412e+00]
 [ 1.83828729e-01 -3.02280690e-01  6.51954863e-01  1.66633248e-01
  -4.76223527e-03 -1.25572521e-01  1.18779078e+00  3.74149440e-01
   9.14113589e-02 -6.09414718e-01  2.23085342e-01 -4.36922299e-02
   4.80998910e-01 -