In [1]:
import numpy as np

In this script, we would like to build a simple, generalized neural network with n features (each input data has n values) and m outputs with only one hidden layer with k neurons.

In [2]:
dataset = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0]])
output = np.array([[0, 0, 1], [1, 0, 0], [1, 1, 0], [0, 1, 1], [0, 0, 1]])
print("The data set is: \n", dataset, "\n")
print("The output is: \n", output)

The data set is: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]] 

The output is: 
 [[0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]]


In [6]:
#Augment the input matrix to implement also the bias parameter on the input layer
b1 = np.ones([dataset.shape[0], 1])
dataset1 = np.hstack((dataset, b1))

#number of neurons
nn = 9

#initialize the first weight matrix:
W_1 = np.random.random([dataset1.shape[1], nn])

#intialize the second weight matrix, consider also the bias parameter:
W_2 = np.random.random([nn + 1, output.shape[1]])

#activation function:
def sig(x):
    return 1 / (1 + np.exp(-x))

#derivative of sigmoid:
def dsig(x):
    return x * (1 - x)

In [7]:
#learning rate
lr =  0.9

In [8]:
i = 0
err = 100
while i<100000:
    if err < 1e-2:
        break
        
    i += 1
    
    #update the predicted values:
    z = sig(np.dot(dataset1, W_1))
    
    #augment z to include the bias parameter in the hidden layer
    b2 = np.ones([z.shape[0], 1])
    z = np.hstack((z, b2))
    pred_out = sig(np.dot(z, W_2))
    
    #compute:
    err = 0.5 * np.linalg.norm(output - pred_out, 2)
    
    #back propagation using gradient descent method:
    dW_2 = np.dot(z.T, -(output - pred_out) * dsig(pred_out))
    dW_1 = np.zeros_like(W_1)
    W_2t = W_2[:-1,:]
    zt = z[:,:-1]
    for j in range(dW_1.shape[0]):
        for k in range(dW_1.shape[1]):
            dW_1[j, k] = np.dot(W_2t[k,:], np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(zt)[:,k] * dataset1[:,j]))
    
    #update the weight matrix
    W_1 -= lr * dW_1
    W_2 -= lr * dW_2
    

print("Finish with",i, "iteration(s) with error", err,".")
print("\nThe weight matrix from the input to the hidden layer: \n", W_1)
print("\nThe weight matrix from the hidden to the output layer: \n", W_2)
print("\nThe final predicted output: \n", pred_out)

Finish with 11156 iteration(s) with error 0.009999613591835857 .

The weight matrix from the input to the hidden layer: 
 [[ 0.46321522  3.9780876  -1.78395144 -1.5316459   4.49019674  3.36862295
   7.0687091  -4.46325401  4.44837483]
 [ 0.73971997  4.03361462  1.31156029  0.92062563  3.44179752  3.4944368
   0.13387993  5.09925853  4.74662556]
 [ 0.78764856  0.3357085  -0.014099    0.12072597 -3.38104468  0.0958561
  -0.46679322  0.21819846  0.48259419]
 [ 1.09207426 -1.678462    1.13865122  0.23256226 -2.55343026 -1.05329473
  -3.18843099  2.22581689 -2.08890432]]

The weight matrix from the hidden to the output layer: 
 [[-0.18545136  0.03343757  0.76051516]
 [ 1.34237864  4.73863332 -1.18176951]
 [-1.98593861 -1.04595488  1.44338386]
 [-1.67105033 -0.12159134  1.1979797 ]
 [ 2.30280604 -6.70418254 -2.27428687]
 [ 0.69177529  3.77216356 -0.90537113]
 [ 7.27455348 -5.54667155 -7.5639277 ]
 [-2.30259171 -6.46737666  2.57491323]
 [ 0.74235595  6.15412037 -0.49801162]
 [-2.39133341 -1.0