In [25]:
import numpy as np

In this script, we would like to build a simple, generalized neural network with n features (each input data has n values) and m outputs with only one hidden layer with k neurons.

In [30]:
dataset = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0]])
output = np.array([[0, 0, 1], [1, 0, 0], [1, 1, 0], [0, 1, 1], [0, 0, 1]])
print("The data set is: \n", dataset, "\n")
print("The output is: \n", output)

The data set is: 
 [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 0]] 

The output is: 
 [[0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]]


In [37]:
#Augment the input matrix to implement also the bias parameter on the input layer
b1 = np.ones([dataset.shape[0], 1])
dataset1 = np.hstack((dataset, b1))

#number of neurons
nn = 100

#initialize the first weight matrix:
W_1 = np.random.random([dataset1.shape[1], nn])

#intialize the second weight matrix, consider also the bias parameter:
W_2 = np.random.random([nn + 1, output.shape[1]])

#activation function:
def sig(x):
    return 1 / (1 + np.exp(-x))

#derivative of sigmoid:
def dsig(x):
    return x * (1 - x)

In [38]:
#learning rate
lr =  0.9

In [39]:
i = 0
err = 100
while i<100000:
    if err < 1e-2:
        break
        
    i += 1
    
    #update the predicted values:
    z = sig(np.dot(dataset1, W_1))
    
    #augment z to include the bias parameter in the hidden layer
    b2 = np.ones([z.shape[0], 1])
    z = np.hstack((z, b2))
    pred_out = sig(np.dot(z, W_2))
    
    #compute:
    err = 0.5 * np.linalg.norm(output - pred_out, 2)
    
    #back propagation using gradient descent method:
    dW_2 = np.dot(z.T, -(output - pred_out) * dsig(pred_out))
    dW_1 = np.zeros_like(W_1)
    for j in range(dW_1.shape[0]):
        for k in range(dW_1.shape[1]):
            dW_1[j, k] = np.dot(W_2[k,:], np.dot(-(output - pred_out).T * dsig(pred_out).T, dsig(z)[:,k] * dataset1[:,j]))
    
    #update the weight matrix
    W_1 -= lr * dW_1
    W_2 -= lr * dW_2
    

print("Finish with",i, "iteration(s) with error", err,".")
print("\nThe weight matrix from the input to the hidden layer: \n", W_1)
print("\nThe weight matrix from the hidden to the output layer: \n", W_2)
print("\nThe final predicted output: \n", pred_out)

KeyboardInterrupt: 